/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Acquisition {
    #[serde(rename = "acquired", skip_serializing_if = "Option::is_none")]
    pub acquired: Option<Vec<crate::models::AcquiredCompany>>,
    #[serde(rename = "acquired_by", skip_serializing_if = "Option::is_none")]
    pub acquired_by: Option<Box<crate::models::Acquisitor>>,
}

impl Acquisition {
    pub fn new() -> Acquisition {
        Acquisition {
            acquired: None,
            acquired_by: None,
        }
    }
}
