/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CompanyDetails {
    /// IPO status of the company
    #[serde(
        rename = "ipo_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ipo_status: Option<Option<String>>,
    /// A measure of prominence of this company by Crunchbase
    #[serde(
        rename = "crunchbase_rank",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub crunchbase_rank: Option<Option<i32>>,
    #[serde(rename = "founding_date", skip_serializing_if = "Option::is_none")]
    pub founding_date: Option<Box<crate::models::Date>>,
    /// Status of the company's operational status
    #[serde(
        rename = "operating_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub operating_status: Option<Option<String>>,
    /// Type of company
    #[serde(
        rename = "company_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub company_type: Option<Option<String>>,
    /// General contact email of the company
    #[serde(
        rename = "contact_email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub contact_email: Option<Option<String>>,
    /// General contact number of the company
    #[serde(
        rename = "phone_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    /// ID of the company's official Facebook account
    #[serde(
        rename = "facebook_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub facebook_id: Option<Option<String>>,
    /// ID of the company's official Twitter account
    #[serde(
        rename = "twitter_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub twitter_id: Option<Option<String>>,
    /// Total rounds of funding that this company has raised
    #[serde(
        rename = "number_of_funding_rounds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_funding_rounds: Option<Option<i32>>,
    /// Total venture capital raised by this company
    #[serde(
        rename = "total_funding_amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_funding_amount: Option<Option<i32>>,
    /// Stock symbol of this public company
    #[serde(
        rename = "stock_symbol",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stock_symbol: Option<Option<String>>,
    #[serde(rename = "ipo_date", skip_serializing_if = "Option::is_none")]
    pub ipo_date: Option<Box<crate::models::Date>>,
    /// Total lead investors
    #[serde(
        rename = "number_of_lead_investors",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_lead_investors: Option<Option<i32>>,
    /// Total investors
    #[serde(
        rename = "number_of_investors",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_investors: Option<Option<i32>>,
    ///          The total amount of funds raised (by this VC firm) to be deployed as         subsidiary investments (applicable only for VC firms)         
    #[serde(
        rename = "total_fund_raised",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_fund_raised: Option<Option<i32>>,
    ///          Total investments made by this VC firm (applicable only for VC firms)         
    #[serde(
        rename = "number_of_investments",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_investments: Option<Option<i32>>,
    ///          Total investments that was led by this VC firm         (applicable only for VC firms)         
    #[serde(
        rename = "number_of_lead_investments",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_lead_investments: Option<Option<i32>>,
    /// Total exits by this VC (applicable only for VC firms)
    #[serde(
        rename = "number_of_exits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_exits: Option<Option<i32>>,
    /// Total companies acquired by this company
    #[serde(
        rename = "number_of_acquisitions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_acquisitions: Option<Option<i32>>,
}

impl CompanyDetails {
    pub fn new() -> CompanyDetails {
        CompanyDetails {
            ipo_status: None,
            crunchbase_rank: None,
            founding_date: None,
            operating_status: None,
            company_type: None,
            contact_email: None,
            phone_number: None,
            facebook_id: None,
            twitter_id: None,
            number_of_funding_rounds: None,
            total_funding_amount: None,
            stock_symbol: None,
            ipo_date: None,
            number_of_lead_investors: None,
            number_of_investors: None,
            total_fund_raised: None,
            number_of_investments: None,
            number_of_lead_investments: None,
            number_of_exits: None,
            number_of_acquisitions: None,
        }
    }
}
