/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CompanySocialNetworkingService {
    #[serde(
        rename = "service",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub service: Option<Option<String>>,
    #[serde(
        rename = "canonical_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub canonical_url: Option<Option<String>>,
    #[serde(
        rename = "internal_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub internal_id: Option<Option<String>>,
}

impl CompanySocialNetworkingService {
    pub fn new() -> CompanySocialNetworkingService {
        CompanySocialNetworkingService {
            service: None,
            canonical_url: None,
            internal_id: None,
        }
    }
}
