/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreditBalance {
    /// Your current credit(s)
    #[serde(rename = "credit_balance", skip_serializing_if = "Option::is_none")]
    pub credit_balance: Option<i32>,
}

impl CreditBalance {
    pub fn new() -> CreditBalance {
        CreditBalance {
            credit_balance: None,
        }
    }
}
