/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmployeeList {
    #[serde(rename = "employees", skip_serializing_if = "Option::is_none")]
    pub employees: Option<Vec<crate::models::Employee>>,
    #[serde(
        rename = "next_page",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page: Option<Option<String>>,
}

impl EmployeeList {
    pub fn new() -> EmployeeList {
        EmployeeList {
            employees: None,
            next_page: None,
        }
    }
}
