/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Exit {
    /// LinkedIn Profile URL of the company that has exited
    #[serde(
        rename = "linkedin_profile_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub linkedin_profile_url: Option<Option<String>>,
    /// Crunchbase Profile URL of the company that has exited
    #[serde(
        rename = "crunchbase_profile_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub crunchbase_profile_url: Option<Option<String>>,
    /// Name of the company
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
}

impl Exit {
    pub fn new() -> Exit {
        Exit {
            linkedin_profile_url: None,
            crunchbase_profile_url: None,
            name: None,
        }
    }
}
