/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JobListPage {
    #[serde(rename = "job", skip_serializing_if = "Option::is_none")]
    pub job: Option<Vec<crate::models::JobListEntry>>,
    #[serde(
        rename = "next_page_no",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_no: Option<Option<i32>>,
    #[serde(
        rename = "next_page_api_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_api_url: Option<Option<String>>,
    #[serde(
        rename = "previous_page_no",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub previous_page_no: Option<Option<i32>>,
    #[serde(
        rename = "previous_page_api_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub previous_page_api_url: Option<Option<String>>,
}

impl JobListPage {
    pub fn new() -> JobListPage {
        JobListPage {
            job: None,
            next_page_no: None,
            next_page_api_url: None,
            previous_page_no: None,
            previous_page_api_url: None,
        }
    }
}
