/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JobListEntry {
    ///          The name of the company that posted this job.         
    #[serde(
        rename = "company",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub company: Option<Option<String>>,
    ///          The LinkedIn Company Profile URL that posted this job.         
    #[serde(
        rename = "company_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub company_url: Option<Option<String>>,
    ///          Job title of the posted job.         
    #[serde(
        rename = "job_title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub job_title: Option<Option<String>>,
    ///          Job Profile URL. You can fetch details about this job using this URL via the [Job Profile API Endpoint](https://nubela.co/proxycurl/docs#jobs-api-job-profile-endpoint).         
    #[serde(
        rename = "job_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub job_url: Option<Option<String>>,
    ///          The date that this job was listed.         
    #[serde(
        rename = "list_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub list_date: Option<Option<String>>,
    ///          The job location.         
    #[serde(
        rename = "location",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub location: Option<Option<String>>,
}

impl JobListEntry {
    pub fn new() -> JobListEntry {
        JobListEntry {
            company: None,
            company_url: None,
            job_title: None,
            job_url: None,
            list_date: None,
            location: None,
        }
    }
}
