/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonExtra {
    /// This profile's Github account.
    #[serde(
        rename = "github_profile_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub github_profile_id: Option<Option<String>>,
    /// This profile's Facebook account.
    #[serde(
        rename = "facebook_profile_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub facebook_profile_id: Option<Option<String>>,
    /// This profile's twitter account.
    #[serde(
        rename = "twitter_profile_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub twitter_profile_id: Option<Option<String>>,
}

impl PersonExtra {
    pub fn new() -> PersonExtra {
        PersonExtra {
            github_profile_id: None,
            facebook_profile_id: None,
            twitter_profile_id: None,
        }
    }
}
