/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProfilePicture {
    ///              Temporary URL to the profile picture (valid for just 30 minutes).             See this [blog post](https://nubela.co/blog/why-is-the-api-returning-s3-links-for-profile-pictures-scraped-from-linkedin-profiles/) for more information.
    #[serde(
        rename = "tmp_profile_pic_url",
        skip_serializing_if = "Option::is_none"
    )]
    pub tmp_profile_pic_url: Option<String>,
}

impl ProfilePicture {
    pub fn new() -> ProfilePicture {
        ProfilePicture {
            tmp_profile_pic_url: None,
        }
    }
}
