/*
 * Proxycurl API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TestScore {
    ///                  Title of the course for which test score was derived from.             
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// Test score
    #[serde(
        rename = "score",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub score: Option<Option<String>>,
    #[serde(rename = "date_on", skip_serializing_if = "Option::is_none")]
    pub date_on: Option<Box<crate::models::Date>>,
    /// Description of the test score.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
}

impl TestScore {
    pub fn new() -> TestScore {
        TestScore {
            name: None,
            score: None,
            date_on: None,
            description: None,
        }
    }
}
